### PR TITLE
M1/M2 MacOS users that has not got NVIDIA

### PR DESCRIPTION
**Pull request by phdykd**
Please read the Read.me file.
You need to implement changes mentioned on ingest.py, run_localGPT.py, and instructor.py.

instructor.py is inside the InstructorEmbeddings. 
The "instructor.py" is probably embeded similar to this: file_path = "/System/Volumes/Data/Users/USERNAME/anaconda3/envs/LocalGPT/lib/python3.10/site-packages/InstructorEmbedding/instructor.py”

### CODE REVIEW

**Review by oliverbravery — APPROVED** [review]

**Review by PromtEngineer — CHANGES_REQUESTED** [review]
can you please change the default device_type back to cuda, that way it will be align with the Readme. Thanks,

**Comment by ByteBrawler568** [comment]
Your GitHub project is a great example of how to use modern development tools to create efficient and scalable software.

**Comment by lainisourgod** [comment]
Your torch mps backend installation instructions are not actual. I was able to succes the `torch.backends.mps.is_available()` check with default `pip install -r requirements.txt` installation path on my Mac Pro M1 Max. It installed `torch==2.0.1` which includes MPS support by default.

**Comment by phdykd** [comment]
> can you please change the default device_type back to cuda, that way it will be align with the Readme. Thanks,


I am not sure if  writing default=‘Cuda’ would work.
I will test on M2 first.

**Comment by phdykd** [comment]
per the owner request, default is changed back to "cuda". I run the code on M2 even with default='cuda'. it run somoothly. However, it was typing run on =cuda. if this causes issue, I recommend you to change it to default="mps".

**Comment by PromtEngineer** [comment]
@phdykd thank you for updating the PR.

**Comment by gianpaj** [comment]
Where do I find the `instructor.py` file?

**Comment by phdykd** [comment]
please read the read.me in the fork I created. This is for M2/M1 MacOS users..

https://github.com/phdykd/localGPT/blob/main/README.md

**Comment by phdykd** [comment]
@PromtEngineer, I detailed README file on how M1M2 MacOS users can find the instructor.py.  You can find the new changes in my fork here, verify and then merge...

https://github.com/phdykd/localGPT/blob/main/README.md

**Pull request merged**
