### PR TITLE
Added feature to save the user questions and model answers to CSV bas…

### PR DESCRIPTION
**Pull request by kevinmgamboa**
To me is very useful to store the questions and answers from my interactions with the model .. so I thought maybe useful for you or others. You will just need to specify a flag as follows:

`python chatGPT.py --save_q&a`

### CODE REVIEW

**Comment by PromtEngineer** [comment]
@kevinmgamboa thanks for putting this together. This is a great functionality. I will test and merge it.

**Comment by aditrukiera99** [comment]
This will be a great improvement !!

**Comment by kevinmgamboa** [comment]
Sorry @PromtEngineer, the PR has a couple of bugs that I just fixed and tested ... seems to work correctly now.

Sorry for the delay in fixing it !!

**Comment by kevinmgamboa** [comment]
> @kevinmgamboa thanks for putting this together. This is a great functionality. I will test and merge it.

Just fixed some bugs ... it should work now and it is up to date with your branch

**Comment by PromtEngineer** [comment]
@kevinmgamboa thanks, will test it and let you know if I run into any issues.

**Comment by clearsitedesigns** [comment]
THis is something I do as well in a number of complex ways:) This is a great feature!

**Pull request merged**
