### PR TITLE
Issue 72: Refactor document loading, add device selection, and update README

### PR DESCRIPTION
**Pull request by teleprint-me**
This pull request addresses Issue #72 and includes the following changes:

1. Refactor document loading in `ingest.py` to utilize the `DOCUMENT_MAP` dictionary from `constants.py`. This improves modularity and allows for easier addition of new document loaders. (Commit: a4c0fee)

2. Add the option to select the device type when running `ingest.py`. The default device is set to "cuda". Users can now specify the device using the `--device_type` argument. The README.md file has been updated to include instructions on device selection and how to see the full list of supported devices. (Commit: a4c0fee)

3. Update the README.md file to include instructions on using the `--device_type` argument and provide details on the supported devices. This enhances the documentation and helps users understand the device selection functionality. (Commit: fb244cb)

4. Ignore generated database results by adding appropriate rules to the gitignore file. (Commit: 3d1806d)

5. Add git ignore rules for Python files to ensure generated files and temporary files are not committed. (Commit: 3ebb267)

These changes improve the flexibility and modularity of the codebase, enhance the documentation, and ensure unwanted files are excluded from version control.

### CODE REVIEW

**Comment by PromtEngineer** [comment]
This looks good, however, I would like to request a couple of more updates. 
1. Can you please also update the ` run_localGPT.py` file so it has similar options for device_type as the` ingest.py`. This will ensure consistency across the code base
2. Support for other file types was added, see - #44 
Can you please integrate those as part of this PR. 
Thanks

**Comment by teleprint-me** [comment]
Why not use `ConfluenceLoader` or `UnstructuredExcelLoader`? Couldn't we use those to load Excel based files?

**Comment by PromtEngineer** [comment]
You are right, it's a much better approach. We can also loaders for other file types (DOC, EPub, etc.) directly supported by long-chain. Can you please add those as part of the PR? Thanks

**Comment by PromtEngineer** [comment]
I also like the last option. It will be more standardized. We can experiment with `0.0.191` to ensure it doesn't break anything else.

**Comment by PromtEngineer** [comment]
@teleprint-me Thanks for this PR and for adding my requests. Looking forward to your contributions to this project.

**Comment by teleprint-me** [comment]
The funny part is I can't run the code. My hardware is out of date. 😉😇

**Comment by PromtEngineer** [comment]
I tested it and it worked :)

**Comment by teleprint-me** [comment]
Is it alright if I use `ingest.py` as a basis in other code? 

I was able to get `ingest.py` to work with CPU. I don't have enough RAM for `run_localGPT.py` using the HF models and I can run a GGML 7B model (inference is slow).

If I come up with anything useful that's within scope, I can probably use it as a basis to contribute in the future. It would be cheaper to do local embeddings over using OpenAI Embeddings as well.

**Comment by PromtEngineer** [comment]
Yes, please free to do that. Looking forward to your contribution.

**Pull request merged**
