### PR TITLE
133 use GitHub actions and pre commit

### LINKED ISSUE #133: Use GitHub Actions and Pre-commit
I was thinking since there are many pull requests from many people, it is probably a good idea to set up GitHub Actions. One of the jobs can be to run pre-commit to make sure all conventions are met. GitHub actions will also be very useful (almost necessary) when there are some automated tests

### PR DESCRIPTION
**Pull request by AhmedHathout**
It is probably better to review changes commit by commit rather than all commits in one go. 

Changes:- 
- Adds the files needed for [pre-commit](https://[pre-commit](https://pre-commit.com/).com/). This will ensure better code quality for the subsequent merge requests (after this one is merged). 
- It also configures GitHub Actions to make sure that pre-commit will run even if the contributor forgets too.  It will fail if the criteria are not met. Have a look at the [forked repo](https://github.com/AhmedHathout/localGPT/actions) for examples (and also to check that the last push did not fail)
- Added CONTRIBUTING.md to explain how to contribute (and mention how to use pre-commit). File is probably not complete but it covers more than what this PR does
- Added ACKNOWLEDGMENT.md

Closes #133

### CODE REVIEW

**Comment by PromtEngineer** [comment]
@AhmedHathout the pre-commit failed on your PR, can you please have a look at it.

**Comment by AhmedHathout** [comment]
I will fix it tomorrow evening (UK time) or the day after and mention you. I will need to force push and rebase but once I do that, I will need you to please merge it before any other pull request because it will conflict with all of them (it touches every second line or so in the codebase)

**Comment by AhmedHathout** [comment]
It is done now @PromtEngineer. Please merge this PR on the main branch before merging any other PR otherwise there will be conflicts. Thanks

**Comment by PromtEngineer** [comment]
@AhmedHathout thank you for helping with it. I have merged the PR. Looking forward to more contributions.

**Comment by AhmedHathout** [comment]
You are welcome! Thank you for creating and maintaining this project. Will try to contribute more 👍

**Pull request merged**
