### PR TITLE
ggml quant cpu mps support

### PR DESCRIPTION
**Pull request by imjwang**
To use MPS, you have to install llama-cpp-python with these env vars:
```bash
export CMAKE_ARGS="-DLLAMA_METAL=on"
export FORCE_CMAKE=1
```
otherwise run this to upgrade from current:
```bash
CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install -U llama-cpp-python --no-cache-dir
```

To validate MPS, check if this shows on run:
Screenshot 2023-06-28 at 5 10 13 PM

### CODE REVIEW

**Comment by PromtEngineer** [comment]
@imjwang can you please check #180. This is going to be the foundation of the new codebase. Do you think it will be possible to combine this PR with that?

**Comment by imjwang** [comment]
@PromtEngineer Yes certainly, let me know what you need. I'm happy to work on it after #180 merges, or let me know how I can help

**Comment by PromtEngineer** [comment]
@imjwang I tested the PR and I think we will go ahead and merge it. Can you please update the Readme as well. We will have to add this functionality to #180 when its ready. Thanks

**Comment by imjwang** [comment]
@PromtEngineer Hey, I just upgraded the Readme. lmk if it's clear

**Pull request merged**
