### PR TITLE
cuBLAS support for GGML Models

### PR DESCRIPTION
**Pull request by imjwang**
cuBLAS support for GGML Models as pointed out in #242 
Currently there is no way to use GPU for GGML because using GGML is triggered by being on cpu or mps, [line 47 from run_localGPT.py](https://github.com/PromtEngineer/localGPT/blob/6f894706d9c371115d691f0d9e3b117fb42ba216/run_localGPT.py#L46C1-L46C1)
This is especially undesirable because the default behavior is to use llama 2 GGML and gpu is unused :'(

This ticket changes ggml logic to 
```python 
if ".ggml" in model_basename:
```
to match the current method of checking gptq with 
```python 
if ".safetensors" in model_basename:
```

LlamaCpp model is being instantiated with kwargs:
```python
            kwargs = {
                "model_path": model_path,
                "n_ctx": max_ctx_size,
                "max_tokens": max_ctx_size,
            }
            if device_type.lower() == "mps":
                kwargs["n_gpu_layers"] = 1000
            if device_type.lower() == "cuda":
                kwargs["n_gpu_layers"] = 1000
                kwargs["n_batch"] = max_ctx_size
            return LlamaCpp(**kwargs)
```
Note:
You need these flags when installing llama-python-cpp: `CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 `
I added to README.
Sources:
https://python.langchain.com/docs/modules/model_io/models/llms/integrations/llamacpp#gpu
https://github.com/abetlen/llama-cpp-python#installation-with-openblas--cublas--clblast--metal

I do not have a GPU, but I used on Colab and here is the output - notice the `BLAS = 1` count, `llama_model_load_internal: offloaded 35/35 layers to GPU`, and inference speeds on V100:
```bash
!python run_localGPT.py --device_type cuda
```
```bash
2023-07-24 00:51:03.445598: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-07-24 00:51:06,689 - INFO - run_localGPT.py:178 - Running on: cuda
2023-07-24 00:51:06,689 - INFO - run_localGPT.py:179 - Display Source Documents set to: False
2023-07-24 00:51:06,880 - INFO - SentenceTransformer.py:66 - Load pretrained SentenceTransformer: hkunlp/instructor-large
load INSTRUCTOR_Transformer
max_seq_length  512
2023-07-24 00:51:10,752 - INFO - __init__.py:88 - Running Chroma using direct local API.
2023-07-24 00:51:10,765 - WARNING - __init__.py:43 - Using embedded DuckDB with persistence: data will be stored in: /content/localGPT/DB
2023-07-24 00:51:10,772 - INFO - ctypes.py:22 - Successfully imported ClickHouse Connect C data optimizations
2023-07-24 00:51:10,779 - INFO - json_impl.py:45 - Using python library for writing JSON byte strings
2023-07-24 00:51:10,829 - INFO - duckdb.py:460 - loaded in 72 embeddings
2023-07-24 00:51:10,831 - INFO - duckdb.py:472 - loaded in 1 collections
2023-07-24 00:51:10,832 - INFO - duckdb.py:89 - collection with name langchain already exists, returning existing collection
2023-07-24 00:51:10,832 - INFO - run_localGPT.py:43 - Loading Model: TheBloke/Llama-2-7B-Chat-GGML, on: cuda
2023-07-24 00:51:10,832 - INFO - run_localGPT.py:44 - This action can take a few minutes!
2023-07-24 00:51:10,832 - INFO - run_localGPT.py:48 - Using Llamacpp for GGML quantized models
ggml_init_cublas: found 1 CUDA devices:
  Device 0: Tesla V100-SXM2-16GB
llama.cpp: loading model from /root/.cache/huggingface/hub/models--TheBloke--Llama-2-7B-Chat-GGML/snapshots/501a3c8182cd256a859888fff4e838c049d5d7f6/llama-2-7b-chat.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 1862.38 MB (+ 1026.00 MB per state)
llama_model_load_internal: allocating batch_size x 1 MB = 512 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 32 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 35/35 layers to GPU
llama_model_load_internal: total VRAM used: 5084 MB
llama_new_context_with_model: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 | 

Enter a query: write a poem on alexander hamilton

llama_print_timings:        load time =  1872.60 ms
llama_print_timings:      sample time =   223.43 ms /   218 runs   (    1.02 ms per token,   975.70 tokens per second)
llama_print_timings: prompt eval time =  1872.37 ms /  1123 tokens (    1.67 ms per token,   599.78 tokens per second)
llama_print_timings:        eval time =  3977.00 ms /   217 runs   (   18.33 ms per token,    54.56 tokens per second)
llama_print_timings:       total time =  6753.88 ms


> Question:
write a poem on alexander hamilton

> Answer:
 I can certainly try! Here's a poem about Alexander Hamilton:
Alexander Hamilton, man of great might,
Father of our country, with all your might.
You shaped this nation with your vision so bright,
And left behind a legacy that's a true sight.
Your passion and perseverance paved the way,
For us to live in freedom and peace each day.
From immigrant to statesman, you rose to fame,
With eloquence and wit, you led the game.
In the Federalist Papers, your words of art,
Helped form our government, a work of heart.
You fought for justice and equality with all your might,
And left behind a legacy that's shining bright.
Your legacy lives on, a beacon of hope,
A testament to the power of perseverance and scope.
So here's to Alexander Hamilton, man of great might,
A hero who shaped our nation with all your might!
```

### CODE REVIEW

**Comment by PromtEngineer** [comment]
@imjwang this is great, I was actually testing a similar update on my end. I will test this version.

**Comment by bannsec** [comment]
This PR appears to work for me. I'm running it in WSL2 -> nvidia docker container and it loads/utilizes GPU as i would expect.

One slight issue (though for a different PR) is that the context_size is static at 2048. Llama 2 has the size of 4096 now, and other models (like superhot versions, mpt, whatever) have different sizes as well. That should likely be pulled out into a variable you can throw on to the command-line.

**Comment by imjwang** [comment]
@bannsec I agree, and thanks for testing.
The reason I am hesitant to pull it out for this pr is because there are a lot of variables that could be pulled out. And I think the solution to pulling out variables is in #180. 
I leave it up to @PromtEngineer for what to do for now.

**Comment by PromtEngineer** [comment]
@bannsec I agree, that needs to be changed and as @imjwang suggested #180 is the right solution. I am trying to make time for testing. Will be going that direction soon.

**Pull request merged**
