### PR TITLE
UIV1.1

### PR DESCRIPTION
**Pull request by LeafmanZ**
Made a few quality of life changes to the UI. Made it so it doesn't need to write to a temp folder anymore. (All uploaded documents are just stored in memory before firing it the API now). Fixed the front end, so when enter is pressed the effect is the exact same as clicking the search button.

### CODE REVIEW

**Comment by PromtEngineer** [comment]
@LeafmanZ the PR is failing the pre-commit. can you please look at it? The update looks good to me and I will merge it once this is resolved. Thanks,

**Comment by LeafmanZ** [comment]
Fixed. A lot of the changes ended up being white space stuff that the pre-commit decided to change in the javascript and css dependencies.

**Comment by PromtEngineer** [comment]
@LeafmanZ thanks, one last check, do we need to update the Readme with the changes?

**Comment by LeafmanZ** [comment]
@PromtEngineer No changes to the Readme needed. The whole process works as is.

**Pull request merged**
